package {
	/**
	 * This file was automatically generated by Jorjon Framework's Resource File Generator.
	 * It contains all resources of the game.
	 * @author Jorjon
	 */
	public class Resources {

		// -- [assets] --
		// ---- [graphics_16] ----
		[Embed(source = "graphics_16/icon_angry.gif")] static public const icon_angry_gif:Class;
		[Embed(source = "graphics_16/icon_grid.gif")] static public const icon_grid_gif:Class;
		[Embed(source = "graphics_16/icon_happy.gif")] static public const icon_happy_gif:Class;
		[Embed(source = "graphics_16/icon_neutral.gif")] static public const icon_neutral_gif:Class;
		[Embed(source = "graphics_16/icon_shape_circle.gif")] static public const icon_shape_circle_gif:Class;
		[Embed(source = "graphics_16/icon_shape_square.gif")] static public const icon_shape_square_gif:Class;
		[Embed(source = "graphics_16/icon_shape_tri.gif")] static public const icon_shape_tri_gif:Class;
		[Embed(source = "graphics_16/icon_surprise.gif")] static public const icon_surprise_gif:Class;
		[Embed(source = "graphics_16/tool_eraser.gif")] static public const tool_eraser_gif:Class;
		[Embed(source = "graphics_16/tool_fill.gif")] static public const tool_fill_gif:Class;
		[Embed(source = "graphics_16/tool_pencil.gif")] static public const tool_pencil_gif:Class;
		[Embed(source = "graphics_16/tool_picker.gif")] static public const tool_picker_gif:Class;
		[Embed(source = "graphics_16/tool_select.gif")] static public const tool_select_gif:Class;
		[Embed(source = "graphics_16/tool_shape.gif")] static public const tool_shape_gif:Class;

		// ---- [other_images] ----
		[Embed(source = "other_images/TransparencyGrid.gif")] static public const transparencygrid_gif:Class;

		[Embed(source = "./Assets.as")] static public const assets_as:Class;
		[Embed(source = "./AssetsGen.as")] static public const assetsgen_as:Class;
		[Embed(source = "./Icons_Pixelshop.psd")] static public const icons_pixelshop_psd:Class;
		[Embed(source = "./atlas.png")] static public const atlas_png:Class;
		[Embed(source = "./atlas.tps")] static public const atlas_tps:Class;
		[Embed(source = "./atlas.xml", mimeType = "application/octet-stream")] static public const atlas_xml:Class;

	}
}